apiVersion: v1
kind: Template
metadata:
  name: tt-rss-template
labels:
  template: tt-rss
  app: tt-rss
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: tt-rss
    partof: tt-rss
  spec:
    template: 
      metadata:
        labels:
          name: tt-rss
          partof: tt-rss
      spec:
        containers:
        - name: tt-rss
          env:
          - name: MODE
            value: app 
          - name: DB_TYPE
            value: "${DB_TYPE}"
          - name: DB_HOST
            value: "${DB_HOST}"
          - name: DB_USER
            value: "${DB_USER}"
          - name: DB_NAME
            value: "${DB_NAME}"
          - name: DB_PASS
            value: "${DB_PASS}"
          - name: DB_PORT
            value: "${DB_PORT}"
          - name: SELF_URL_PATH
            value: "${SELF_URL_PATH}"
          - name: SINGLE_USER_MODE
            value: "${SINGLE_USER_MODE}"
          image: "tt-rss"
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: "/data"
            name: "datavol"
        - name: tt-rss-updater
          env:
          - name: MODE
            value: updater
          - name: DB_TYPE
            value: "${DB_TYPE}"
          - name: DB_HOST
            value: "${DB_HOST}"
          - name: DB_USER
            value: "${DB_USER}"
          - name: DB_NAME
            value: "${DB_NAME}"
          - name: DB_PASS
            value: "${DB_PASS}"
          - name: DB_PORT
            value: "${DB_PORT}"
          - name: SELF_URL_PATH
            value: "${SELF_URL_PATH}"
          - name: SINGLE_USER_MODE
            value: "${SINGLE_USER_MODE}"
          image: "tt-rss"
          volumeMounts:
          - mountPath: "/data"
            name: "datavol"
        volumes:
        - name: "datavol"
          persistentVolumeClaim:
            claimName: "tt-rss-data-claim"
        securityContext: 
          supplementalGroups: [5555] 
    replicas: 1
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - tt-rss
            - tt-rss-updater
          from:
            kind: ImageStreamTag
            name: "tt-rss:latest"
    strategy: 
      type: Recreate
    paused: false 
    revisionHistoryLimit: 2 
    minReadySeconds: 0

- kind: Service
  apiVersion: v1
  metadata:
    name: tt-rss
  spec:
    selector:
      name: tt-rss
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080

- kind: Route
  apiVersion: v1
  metadata:
    name: tt-rss
  spec:
    host: "${APP_ROUTE_HOST}"
    to:
      kind: Service
      name: tt-rss

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: tt-rss-data-claim
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi

- kind: ImageStream
  apiVersion: v1
  metadata:
      name: "tt-rss"
  spec:
    dockerImageRepository: ""
    tags:
      - name: "latest"

parameters:
- name: APP_ROUTE_HOST
  description: Hostname use for the router object
  value: tt-rss-jojo.apps.lan.terhaak.de
  required: true
- name: DB_TYPE
  description: Database type, mysql or psql
  value: mysql
- name: DB_HOST
  description: Database host
- name: DB_USER
  description: Database user
- name: DB_NAME
  description: Database name
- name: DB_PASS
  description: Database password
- name: DB_PORT
  description: Database port
  value: "3306"
- name: SELF_URL_PATH
  description: Full URL of your tt-rss installation
- name: SINGLE_USER_MODE
  description: Operate in single user mode
